import { ethers } from "hardhat";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log("Account balance:", (await ethers.provider.getBalance(deployer.address)).toString());

  // 1. Deploy MockUSDC (skip on mainnet – use real USDC address)
  const isLocal = (await ethers.provider.getNetwork()).chainId === 31337n;

  let stablecoinAddress: string;
  if (isLocal) {
    const MockUSDC = await ethers.getContractFactory("MockUSDC");
    const usdc = await MockUSDC.deploy();
    await usdc.waitForDeployment();
    stablecoinAddress = await usdc.getAddress();
    console.log("MockUSDC deployed to:", stablecoinAddress);
  } else {
    // Replace with actual USDC address on Plasma
    stablecoinAddress = process.env.STABLECOIN_ADDRESS || "";
    if (!stablecoinAddress) {
      throw new Error("Set STABLECOIN_ADDRESS env var for non-local deployment");
    }
    console.log("Using stablecoin at:", stablecoinAddress);
  }

  // 2. Deploy PayrollRegistry
  const PayrollRegistry = await ethers.getContractFactory("PayrollRegistry");
  const registry = await PayrollRegistry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("PayrollRegistry deployed to:", registryAddress);

  // 3. Deploy PaymentExecutor
  const PaymentExecutor = await ethers.getContractFactory("PaymentExecutor");
  const executor = await PaymentExecutor.deploy(stablecoinAddress, registryAddress);
  await executor.waitForDeployment();
  const executorAddress = await executor.getAddress();
  console.log("PaymentExecutor deployed to:", executorAddress);

  // 4. Authorise PaymentExecutor in PayrollRegistry
  const tx = await registry.setExecutorAuthorised(executorAddress, true);
  await tx.wait();
  console.log("PaymentExecutor authorised in PayrollRegistry");

  // 5. Deploy CredentialVerifier
  //    NOTE: For production you must first deploy the Groth16 Verifier.sol
  //    generated by `snarkjs zkey export solidityverifier`. For local testing
  //    we skip it or deploy a mock. Set ZK_VERIFIER_ADDRESS if available.
  const zkVerifierAddress = process.env.ZK_VERIFIER_ADDRESS;
  if (zkVerifierAddress) {
    const CredentialVerifier = await ethers.getContractFactory("CredentialVerifier");
    const credentialVerifier = await CredentialVerifier.deploy(zkVerifierAddress);
    await credentialVerifier.waitForDeployment();
    console.log("CredentialVerifier deployed to:", await credentialVerifier.getAddress());
  } else {
    console.log("Skipping CredentialVerifier deployment (set ZK_VERIFIER_ADDRESS to deploy)");
  }

  // Summary
  console.log("\n--- Deployment Summary ---");
  console.log("Network:", (await ethers.provider.getNetwork()).name);
  if (isLocal) console.log("MockUSDC:        ", stablecoinAddress);
  console.log("PayrollRegistry: ", registryAddress);
  console.log("PaymentExecutor: ", executorAddress);
  if (zkVerifierAddress) console.log("CredentialVerifier:", zkVerifierAddress);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
